# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# IMPORTANT:
# Dont forget to add 'from .' to avoid errors
from . import ndarray_pb2 as ndarray__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\nflask_grpc\x1a\rndarray.proto\"\x1c\n\rStringMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"=\n\x0eNDArrayMessage\x12+\n\x07ndarray\x18\x01 \x01(\x0b\x32\x1a.numproto.protobuf.NDArray\"A\n\x0cImageMessage\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x32\xe3\x01\n\x0c\x46laskService\x12\x45\n\rStringRequest\x12\x19.flask_grpc.StringMessage\x1a\x19.flask_grpc.StringMessage\x12H\n\x0eNDArrayRequest\x12\x1a.flask_grpc.NDArrayMessage\x1a\x1a.flask_grpc.NDArrayMessage\x12\x42\n\x0cImageRequest\x12\x18.flask_grpc.ImageMessage\x1a\x18.flask_grpc.ImageMessageb\x06proto3')



_STRINGMESSAGE = DESCRIPTOR.message_types_by_name['StringMessage']
_NDARRAYMESSAGE = DESCRIPTOR.message_types_by_name['NDArrayMessage']
_IMAGEMESSAGE = DESCRIPTOR.message_types_by_name['ImageMessage']
StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), {
  'DESCRIPTOR' : _STRINGMESSAGE,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:flask_grpc.StringMessage)
  })
_sym_db.RegisterMessage(StringMessage)

NDArrayMessage = _reflection.GeneratedProtocolMessageType('NDArrayMessage', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAYMESSAGE,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:flask_grpc.NDArrayMessage)
  })
_sym_db.RegisterMessage(NDArrayMessage)

ImageMessage = _reflection.GeneratedProtocolMessageType('ImageMessage', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMESSAGE,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:flask_grpc.ImageMessage)
  })
_sym_db.RegisterMessage(ImageMessage)

_FLASKSERVICE = DESCRIPTOR.services_by_name['FlaskService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGMESSAGE._serialized_start=40
  _STRINGMESSAGE._serialized_end=68
  _NDARRAYMESSAGE._serialized_start=70
  _NDARRAYMESSAGE._serialized_end=131
  _IMAGEMESSAGE._serialized_start=133
  _IMAGEMESSAGE._serialized_end=198
  _FLASKSERVICE._serialized_start=201
  _FLASKSERVICE._serialized_end=428
# @@protoc_insertion_point(module_scope)
